"use client";

import { useState } from "react";
import { motion } from "framer-motion";
import { LEARNING_PATHS, PathGraph, PathSelector } from "./learning-path";

export function LearningPathSection() {
    const [activePath, setActivePath] = useState(LEARNING_PATHS[0]);

    return (
        <section className="relative py-20">
            <div className="relative max-w-7xl mx-auto px-4 sm:px-6">
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true }}
                    className="text-center mb-10"
                >
                    <h2 className="text-3xl font-bold text-white mb-4">
                        AI-Generated Learning Paths
                    </h2>
                    <p className="text-[var(--forge-text-secondary)] max-w-2xl mx-auto">
                        Visualize your journey. Solid nodes are curated content,
                        <span className="text-[var(--gold)]"> ✨ sparkling nodes</span> are dynamically generated by AI for your unique needs.
                    </p>
                </motion.div>

                <div className="flex flex-col lg:flex-row gap-6">
                    <motion.div
                        initial={{ opacity: 0, x: -20 }}
                        whileInView={{ opacity: 1, x: 0 }}
                        viewport={{ once: true }}
                    >
                        <PathSelector
                            paths={LEARNING_PATHS}
                            activePath={activePath}
                            onSelectPath={setActivePath}
                        />
                    </motion.div>

                    <motion.div
                        initial={{ opacity: 0, x: 20 }}
                        whileInView={{ opacity: 1, x: 0 }}
                        viewport={{ once: true }}
                        className="flex-1"
                    >
                        <PathGraph path={activePath} />
                    </motion.div>
                </div>
            </div>
        </section>
    );
}
