/**
 * Predictive Job Postings Data
 *
 * Simulated real-time job posting data with skill requirements and match scores.
 */

import type { PredictiveJobPosting } from "../predictiveTypes";

export const predictiveJobPostings: PredictiveJobPosting[] = [
    {
        id: "job-001",
        company: "Anthropic",
        companySize: "medium",
        title: "Senior AI Engineer",
        seniorityLevel: "senior",
        location: { city: "San Francisco", country: "USA", remote: "hybrid" },
        salary: { min: 200000, max: 350000, currency: "USD", period: "yearly" },
        requiredSkills: [
            { skill: "Python", proficiency: 5, required: true, marketPrevalence: 95 },
            { skill: "PyTorch", proficiency: 4, required: true, marketPrevalence: 78 },
            { skill: "LLM Architecture", proficiency: 4, required: true, marketPrevalence: 45 },
            { skill: "Distributed Systems", proficiency: 3, required: true, marketPrevalence: 60 },
        ],
        preferredSkills: ["Rust", "CUDA", "Research Background"],
        matchScore: 72,
        skillGaps: ["LLM Architecture", "PyTorch"],
        estimatedTimeToQualify: 24,
        postedDate: "2024-12-15",
        applicantCount: 234,
        competitionLevel: "very_high",
    },
    {
        id: "job-002",
        company: "Vercel",
        companySize: "medium",
        title: "Senior Frontend Engineer",
        seniorityLevel: "senior",
        location: { country: "USA", remote: "full" },
        salary: { min: 180000, max: 250000, currency: "USD", period: "yearly" },
        requiredSkills: [
            { skill: "React", proficiency: 5, required: true, marketPrevalence: 92 },
            { skill: "TypeScript", proficiency: 5, required: true, marketPrevalence: 88 },
            { skill: "Next.js", proficiency: 4, required: true, marketPrevalence: 65 },
            { skill: "Performance Optimization", proficiency: 4, required: true, marketPrevalence: 55 },
        ],
        preferredSkills: ["Rust", "WebAssembly", "Design Systems"],
        matchScore: 88,
        skillGaps: ["Performance Optimization"],
        estimatedTimeToQualify: 8,
        postedDate: "2024-12-10",
        applicantCount: 156,
        competitionLevel: "high",
    },
    {
        id: "job-003",
        company: "Stripe",
        companySize: "large",
        title: "Backend Engineer - Payments",
        seniorityLevel: "mid",
        location: { city: "Seattle", country: "USA", remote: "hybrid" },
        salary: { min: 160000, max: 220000, currency: "USD", period: "yearly" },
        requiredSkills: [
            { skill: "Go", proficiency: 4, required: true, marketPrevalence: 70 },
            { skill: "PostgreSQL", proficiency: 4, required: true, marketPrevalence: 82 },
            { skill: "Distributed Systems", proficiency: 3, required: true, marketPrevalence: 65 },
            { skill: "API Design", proficiency: 4, required: true, marketPrevalence: 75 },
        ],
        preferredSkills: ["Ruby", "Payment Systems", "Security"],
        matchScore: 65,
        skillGaps: ["Go", "Distributed Systems"],
        estimatedTimeToQualify: 16,
        postedDate: "2024-12-12",
        applicantCount: 89,
        competitionLevel: "moderate",
    },
    {
        id: "job-004",
        company: "Datadog",
        companySize: "large",
        title: "Platform Engineer",
        seniorityLevel: "senior",
        location: { city: "New York", country: "USA", remote: "hybrid" },
        salary: { min: 170000, max: 240000, currency: "USD", period: "yearly" },
        requiredSkills: [
            { skill: "Kubernetes", proficiency: 5, required: true, marketPrevalence: 85 },
            { skill: "Go", proficiency: 4, required: true, marketPrevalence: 72 },
            { skill: "Terraform", proficiency: 4, required: true, marketPrevalence: 78 },
            { skill: "AWS", proficiency: 4, required: true, marketPrevalence: 88 },
        ],
        preferredSkills: ["Rust", "eBPF", "Prometheus"],
        matchScore: 58,
        skillGaps: ["Kubernetes", "Terraform"],
        estimatedTimeToQualify: 20,
        postedDate: "2024-12-08",
        applicantCount: 67,
        competitionLevel: "moderate",
    },
    {
        id: "job-005",
        company: "OpenAI",
        companySize: "medium",
        title: "Full Stack Engineer - ChatGPT",
        seniorityLevel: "mid",
        location: { city: "San Francisco", country: "USA", remote: "no" },
        salary: { min: 200000, max: 300000, currency: "USD", period: "yearly" },
        requiredSkills: [
            { skill: "React", proficiency: 4, required: true, marketPrevalence: 90 },
            { skill: "Python", proficiency: 4, required: true, marketPrevalence: 88 },
            { skill: "TypeScript", proficiency: 4, required: true, marketPrevalence: 85 },
            { skill: "PostgreSQL", proficiency: 3, required: true, marketPrevalence: 80 },
        ],
        preferredSkills: ["FastAPI", "Redis", "Kubernetes"],
        matchScore: 82,
        skillGaps: ["Python Backend"],
        estimatedTimeToQualify: 10,
        postedDate: "2024-12-14",
        applicantCount: 412,
        competitionLevel: "very_high",
    },
    {
        id: "job-006",
        company: "Figma",
        companySize: "medium",
        title: "Software Engineer - Multiplayer",
        seniorityLevel: "mid",
        location: { city: "San Francisco", country: "USA", remote: "hybrid" },
        salary: { min: 165000, max: 230000, currency: "USD", period: "yearly" },
        requiredSkills: [
            { skill: "TypeScript", proficiency: 5, required: true, marketPrevalence: 88 },
            { skill: "WebSockets", proficiency: 4, required: true, marketPrevalence: 45 },
            { skill: "CRDT", proficiency: 3, required: true, marketPrevalence: 15 },
            { skill: "React", proficiency: 4, required: true, marketPrevalence: 90 },
        ],
        preferredSkills: ["Rust", "WebAssembly", "Canvas API"],
        matchScore: 70,
        skillGaps: ["CRDT", "WebSockets"],
        estimatedTimeToQualify: 14,
        postedDate: "2024-12-11",
        applicantCount: 98,
        competitionLevel: "high",
    },
    {
        id: "job-007",
        company: "Cloudflare",
        companySize: "large",
        title: "Systems Engineer - Workers",
        seniorityLevel: "senior",
        location: { country: "USA", remote: "full" },
        salary: { min: 180000, max: 260000, currency: "USD", period: "yearly" },
        requiredSkills: [
            { skill: "Rust", proficiency: 4, required: true, marketPrevalence: 35 },
            { skill: "V8/JavaScript Engines", proficiency: 3, required: true, marketPrevalence: 20 },
            { skill: "WebAssembly", proficiency: 3, required: true, marketPrevalence: 25 },
            { skill: "Systems Programming", proficiency: 4, required: true, marketPrevalence: 40 },
        ],
        preferredSkills: ["C++", "Go", "Linux Internals"],
        matchScore: 35,
        skillGaps: ["Rust", "V8/JavaScript Engines", "WebAssembly"],
        estimatedTimeToQualify: 32,
        postedDate: "2024-12-09",
        applicantCount: 34,
        competitionLevel: "low",
    },
    {
        id: "job-008",
        company: "Notion",
        companySize: "medium",
        title: "Frontend Engineer",
        seniorityLevel: "mid",
        location: { city: "San Francisco", country: "USA", remote: "hybrid" },
        salary: { min: 150000, max: 210000, currency: "USD", period: "yearly" },
        requiredSkills: [
            { skill: "React", proficiency: 5, required: true, marketPrevalence: 92 },
            { skill: "TypeScript", proficiency: 4, required: true, marketPrevalence: 88 },
            { skill: "CSS/Styling", proficiency: 4, required: true, marketPrevalence: 85 },
            { skill: "State Management", proficiency: 4, required: true, marketPrevalence: 75 },
        ],
        preferredSkills: ["Animation", "Accessibility", "Performance"],
        matchScore: 92,
        skillGaps: [],
        estimatedTimeToQualify: 0,
        postedDate: "2024-12-13",
        applicantCount: 187,
        competitionLevel: "high",
    },
];
