/**
 * Skill Demand Predictions Data
 *
 * Mock data for skill demand predictions and market trends.
 */

import type { SkillDemandPrediction } from "../predictiveTypes";

export const skillDemandPredictions: SkillDemandPrediction[] = [
    {
        skillId: "react",
        skillName: "React",
        currentDemand: 88,
        predictedDemand: 85,
        trend: "stable",
        changePercent: -3,
        confidence: "high",
        horizon: "12m",
        saturationLevel: 72,
        optimalLearningWindow: {
            recommendedStart: "2025-01-01",
            windowCloses: "2025-06-01",
            urgency: "moderate",
            reasoning: "Market mature but still strong demand. Good foundation skill.",
        },
        complementarySkills: ["TypeScript", "Next.js", "React Query", "Zustand"],
        drivingIndustries: ["Tech Startups", "Enterprise", "E-commerce"],
    },
    {
        skillId: "typescript",
        skillName: "TypeScript",
        currentDemand: 85,
        predictedDemand: 92,
        trend: "rising",
        changePercent: 8,
        confidence: "very_high",
        horizon: "12m",
        saturationLevel: 55,
        optimalLearningWindow: {
            recommendedStart: "2025-01-01",
            windowCloses: "2025-12-01",
            urgency: "high",
            reasoning: "Rapidly becoming industry standard. Learn now for competitive advantage.",
        },
        complementarySkills: ["React", "Node.js", "GraphQL", "Zod"],
        drivingIndustries: ["Enterprise", "Fintech", "Tech Startups"],
    },
    {
        skillId: "rust",
        skillName: "Rust",
        currentDemand: 45,
        predictedDemand: 68,
        trend: "emerging",
        changePercent: 51,
        confidence: "medium",
        horizon: "24m",
        saturationLevel: 15,
        optimalLearningWindow: {
            recommendedStart: "2025-03-01",
            windowCloses: "2026-06-01",
            urgency: "low",
            reasoning: "Early mover advantage available. Growing adoption in systems programming.",
        },
        complementarySkills: ["WebAssembly", "Systems Programming", "C++"],
        drivingIndustries: ["Cloud Infrastructure", "Cybersecurity", "Gaming"],
    },
    {
        skillId: "ai-ml",
        skillName: "AI/ML Engineering",
        currentDemand: 92,
        predictedDemand: 98,
        trend: "rising",
        changePercent: 7,
        confidence: "very_high",
        horizon: "12m",
        saturationLevel: 35,
        optimalLearningWindow: {
            recommendedStart: "2025-01-01",
            windowCloses: "2025-09-01",
            urgency: "critical",
            reasoning: "Explosive growth sector. High demand, low saturation. Act fast.",
        },
        complementarySkills: ["Python", "PyTorch", "LangChain", "Vector Databases"],
        drivingIndustries: ["AI/ML", "Tech Startups", "Enterprise", "Healthcare"],
    },
    {
        skillId: "nextjs",
        skillName: "Next.js",
        currentDemand: 78,
        predictedDemand: 88,
        trend: "rising",
        changePercent: 13,
        confidence: "high",
        horizon: "12m",
        saturationLevel: 42,
        optimalLearningWindow: {
            recommendedStart: "2025-01-01",
            windowCloses: "2025-10-01",
            urgency: "high",
            reasoning: "Becoming the default React framework. Strong career ROI.",
        },
        complementarySkills: ["React", "TypeScript", "Vercel", "Server Components"],
        drivingIndustries: ["Tech Startups", "E-commerce", "Enterprise"],
    },
    {
        skillId: "kubernetes",
        skillName: "Kubernetes",
        currentDemand: 82,
        predictedDemand: 86,
        trend: "stable",
        changePercent: 5,
        confidence: "high",
        horizon: "12m",
        saturationLevel: 58,
        optimalLearningWindow: {
            recommendedStart: "2025-02-01",
            windowCloses: "2025-12-01",
            urgency: "moderate",
            reasoning: "Infrastructure standard. Steady demand for DevOps/Platform engineers.",
        },
        complementarySkills: ["Docker", "Terraform", "AWS", "GitOps"],
        drivingIndustries: ["Cloud Infrastructure", "Enterprise", "Fintech"],
    },
    {
        skillId: "golang",
        skillName: "Go",
        currentDemand: 70,
        predictedDemand: 78,
        trend: "rising",
        changePercent: 11,
        confidence: "high",
        horizon: "12m",
        saturationLevel: 38,
        optimalLearningWindow: {
            recommendedStart: "2025-01-01",
            windowCloses: "2025-11-01",
            urgency: "moderate",
            reasoning: "Strong backend/infrastructure demand. Good salary potential.",
        },
        complementarySkills: ["gRPC", "Kubernetes", "PostgreSQL", "Redis"],
        drivingIndustries: ["Cloud Infrastructure", "Fintech", "Enterprise"],
    },
    {
        skillId: "langchain",
        skillName: "LangChain/AI Agents",
        currentDemand: 55,
        predictedDemand: 85,
        trend: "emerging",
        changePercent: 55,
        confidence: "medium",
        horizon: "12m",
        saturationLevel: 12,
        optimalLearningWindow: {
            recommendedStart: "2025-01-01",
            windowCloses: "2025-06-01",
            urgency: "critical",
            reasoning: "First mover advantage in AI agents. Very low competition currently.",
        },
        complementarySkills: ["Python", "OpenAI API", "Vector Databases", "Prompt Engineering"],
        drivingIndustries: ["AI/ML", "Tech Startups", "Enterprise"],
    },
    {
        skillId: "web3",
        skillName: "Web3/Blockchain",
        currentDemand: 35,
        predictedDemand: 28,
        trend: "declining",
        changePercent: -20,
        confidence: "medium",
        horizon: "12m",
        saturationLevel: 65,
        optimalLearningWindow: {
            recommendedStart: "2025-06-01",
            windowCloses: "2026-01-01",
            urgency: "low",
            reasoning: "Market correction ongoing. Wait for stabilization before investing time.",
        },
        complementarySkills: ["Solidity", "Ethereum", "Smart Contracts"],
        drivingIndustries: ["Web3/Blockchain", "Fintech"],
    },
    {
        skillId: "python",
        skillName: "Python",
        currentDemand: 90,
        predictedDemand: 92,
        trend: "stable",
        changePercent: 2,
        confidence: "very_high",
        horizon: "12m",
        saturationLevel: 68,
        optimalLearningWindow: {
            recommendedStart: "2025-01-01",
            windowCloses: "2025-12-01",
            urgency: "moderate",
            reasoning: "Essential for AI/ML and data work. High saturation but still strong demand.",
        },
        complementarySkills: ["FastAPI", "Pandas", "PyTorch", "SQLAlchemy"],
        drivingIndustries: ["AI/ML", "Enterprise", "Fintech", "Healthcare"],
    },
];
