/**
 * Angular Curriculum Nodes (10 nodes)
 * Full-featured platform for enterprise applications
 */

import { CurriculumNode } from "../curriculumTypes";

export const angularNodes: CurriculumNode[] = [
    {
        id: "angular-fundamentals",
        title: "Angular Fundamentals",
        description: "Components, modules, and Angular architecture.",
        category: "angular",
        subcategory: "Core",
        status: "locked",
        estimatedHours: 20,
        difficulty: "intermediate",
        skills: ["Components", "Modules", "Templates"],
        resources: [
            { type: "course", title: "Angular Documentation", url: "#" },
        ],
        position: { x: 2200, y: 80 },
        tier: 2,
    },
    {
        id: "angular-services",
        title: "Services & DI",
        description: "Dependency injection and service patterns.",
        category: "angular",
        subcategory: "Core",
        status: "locked",
        estimatedHours: 10,
        difficulty: "intermediate",
        skills: ["Services", "Dependency Injection", "Providers"],
        resources: [
            { type: "video", title: "Angular DI Deep Dive", url: "#" },
        ],
        position: { x: 2200, y: 160 },
        tier: 2,
    },
    {
        id: "rxjs-basics",
        title: "RxJS Basics",
        description: "Reactive programming with Observables.",
        category: "angular",
        subcategory: "RxJS",
        status: "locked",
        estimatedHours: 15,
        difficulty: "advanced",
        skills: ["Observables", "Operators", "Subjects"],
        resources: [
            { type: "course", title: "RxJS Complete Guide", url: "#" },
        ],
        position: { x: 2200, y: 240 },
        tier: 2,
    },
    {
        id: "angular-router",
        title: "Angular Router",
        description: "Navigation, guards, and lazy loading.",
        category: "angular",
        subcategory: "Routing",
        status: "locked",
        estimatedHours: 10,
        difficulty: "intermediate",
        skills: ["Routes", "Guards", "Resolvers"],
        resources: [
            { type: "article", title: "Angular Routing Guide", url: "#" },
        ],
        position: { x: 2350, y: 160 },
        tier: 2,
    },
    {
        id: "angular-forms",
        title: "Angular Forms",
        description: "Template-driven and reactive forms.",
        category: "angular",
        subcategory: "Forms",
        status: "locked",
        estimatedHours: 12,
        difficulty: "intermediate",
        skills: ["Reactive Forms", "Validation", "FormArray"],
        resources: [
            { type: "video", title: "Angular Forms Mastery", url: "#" },
        ],
        position: { x: 2350, y: 240 },
        tier: 2,
    },
    {
        id: "ngrx",
        title: "NgRx State Management",
        description: "Redux-style state management for Angular.",
        category: "angular",
        subcategory: "State",
        status: "locked",
        estimatedHours: 15,
        difficulty: "advanced",
        skills: ["Store", "Effects", "Selectors"],
        resources: [
            { type: "course", title: "NgRx Complete Course", url: "#" },
        ],
        position: { x: 2200, y: 320 },
        tier: 3,
    },
    {
        id: "angular-testing",
        title: "Testing Angular",
        description: "Unit and integration testing Angular apps.",
        category: "angular",
        subcategory: "Testing",
        status: "locked",
        estimatedHours: 12,
        difficulty: "advanced",
        skills: ["TestBed", "Jasmine", "Component Testing"],
        resources: [
            { type: "video", title: "Angular Testing Guide", url: "#" },
        ],
        position: { x: 2350, y: 320 },
        tier: 3,
    },
    {
        id: "angular-cli",
        title: "Angular CLI",
        description: "Project scaffolding and build configuration.",
        category: "angular",
        subcategory: "Tooling",
        status: "locked",
        estimatedHours: 6,
        difficulty: "intermediate",
        skills: ["ng generate", "Schematics", "Build Config"],
        resources: [
            { type: "article", title: "Angular CLI Reference", url: "#" },
        ],
        position: { x: 2350, y: 80 },
        tier: 2,
    },
    {
        id: "angular-performance",
        title: "Angular Performance",
        description: "Change detection and optimization strategies.",
        category: "angular",
        subcategory: "Performance",
        status: "locked",
        estimatedHours: 10,
        difficulty: "advanced",
        skills: ["OnPush", "TrackBy", "Lazy Loading"],
        resources: [
            { type: "video", title: "Angular Performance Optimization", url: "#" },
        ],
        position: { x: 2275, y: 400 },
        tier: 3,
    },
    {
        id: "angular-signals",
        title: "Angular Signals",
        description: "New reactive primitive for Angular 16+.",
        category: "angular",
        subcategory: "Core",
        status: "locked",
        estimatedHours: 8,
        difficulty: "advanced",
        skills: ["Signals", "Computed", "Effects"],
        resources: [
            { type: "article", title: "Angular Signals Guide", url: "#" },
        ],
        position: { x: 2275, y: 480 },
        tier: 3,
    },
];
