/**
 * Build Tools Curriculum Nodes (8 nodes)
 * Development workflow and build optimization
 */

import { CurriculumNode } from "../curriculumTypes";

export const buildToolsNodes: CurriculumNode[] = [
    {
        id: "npm-package-manager",
        title: "npm & Package Management",
        description: "Install and manage dependencies with npm.",
        category: "build-tools",
        subcategory: "Package Managers",
        status: "in_progress",
        estimatedHours: 6,
        difficulty: "beginner",
        skills: ["npm", "package.json", "Scripts"],
        resources: [
            { type: "article", title: "npm Documentation", url: "#" },
        ],
        position: { x: 550, y: 500 },
        tier: 1,
    },
    {
        id: "pnpm-yarn",
        title: "pnpm & Yarn",
        description: "Alternative package managers for faster installs.",
        category: "build-tools",
        subcategory: "Package Managers",
        status: "available",
        estimatedHours: 4,
        difficulty: "intermediate",
        skills: ["pnpm", "Yarn", "Workspaces"],
        resources: [
            { type: "video", title: "pnpm vs Yarn vs npm", url: "#" },
        ],
        position: { x: 550, y: 580 },
        tier: 1,
    },
    {
        id: "vite",
        title: "Vite",
        description: "Next-generation frontend tooling.",
        category: "build-tools",
        subcategory: "Bundlers",
        status: "locked",
        estimatedHours: 8,
        difficulty: "intermediate",
        skills: ["Dev Server", "HMR", "Build"],
        resources: [
            { type: "course", title: "Vite Documentation", url: "#" },
        ],
        position: { x: 550, y: 660 },
        tier: 2,
    },
    {
        id: "webpack",
        title: "Webpack",
        description: "Powerful and configurable module bundler.",
        category: "build-tools",
        subcategory: "Bundlers",
        status: "locked",
        estimatedHours: 15,
        difficulty: "advanced",
        skills: ["Loaders", "Plugins", "Code Splitting"],
        resources: [
            { type: "video", title: "Webpack Deep Dive", url: "#" },
        ],
        position: { x: 550, y: 740 },
        tier: 2,
    },
    {
        id: "esbuild-swc",
        title: "esbuild & SWC",
        description: "Fast JavaScript/TypeScript compilers.",
        category: "build-tools",
        subcategory: "Compilers",
        status: "locked",
        estimatedHours: 4,
        difficulty: "intermediate",
        skills: ["esbuild", "SWC", "Fast Builds"],
        resources: [
            { type: "article", title: "Modern JS Compilers", url: "#" },
        ],
        position: { x: 700, y: 580 },
        tier: 2,
    },
    {
        id: "monorepos",
        title: "Monorepos",
        description: "Manage multiple packages with Turborepo or Nx.",
        category: "build-tools",
        subcategory: "Architecture",
        status: "locked",
        estimatedHours: 12,
        difficulty: "advanced",
        skills: ["Turborepo", "Nx", "Workspaces"],
        resources: [
            { type: "course", title: "Monorepo Tooling", url: "#" },
        ],
        position: { x: 700, y: 660 },
        tier: 3,
    },
    {
        id: "ci-cd",
        title: "CI/CD Pipelines",
        description: "Automate builds and deployments.",
        category: "build-tools",
        subcategory: "DevOps",
        status: "locked",
        estimatedHours: 10,
        difficulty: "advanced",
        skills: ["GitHub Actions", "Vercel", "Docker"],
        resources: [
            { type: "video", title: "CI/CD for Frontend", url: "#" },
        ],
        position: { x: 700, y: 740 },
        tier: 3,
    },
    {
        id: "linting-formatting",
        title: "Linting & Formatting",
        description: "ESLint, Prettier, and code quality tools.",
        category: "build-tools",
        subcategory: "Quality",
        status: "available",
        estimatedHours: 4,
        difficulty: "beginner",
        skills: ["ESLint", "Prettier", "Husky"],
        resources: [
            { type: "article", title: "Linting Setup Guide", url: "#" },
        ],
        position: { x: 625, y: 820 },
        tier: 1,
    },
];
