/**
 * Design Systems Curriculum Nodes (8 nodes)
 * Scalable component architecture and design consistency
 */

import { CurriculumNode } from "../curriculumTypes";

export const designSystemsNodes: CurriculumNode[] = [
    {
        id: "design-tokens",
        title: "Design Tokens",
        description: "Create and manage design tokens for consistency.",
        category: "design-systems",
        subcategory: "Foundations",
        status: "locked",
        estimatedHours: 8,
        difficulty: "intermediate",
        skills: ["Tokens", "Variables", "Theming"],
        resources: [
            { type: "article", title: "Design Tokens Guide", url: "#" },
        ],
        position: { x: 1450, y: 580 },
        tier: 2,
    },
    {
        id: "component-library",
        title: "Component Libraries",
        description: "Build reusable component libraries.",
        category: "design-systems",
        subcategory: "Components",
        status: "locked",
        estimatedHours: 15,
        difficulty: "advanced",
        skills: ["Component API", "Variants", "Composition"],
        resources: [
            { type: "course", title: "Building Component Libraries", url: "#" },
        ],
        position: { x: 1450, y: 660 },
        tier: 3,
    },
    {
        id: "storybook",
        title: "Storybook",
        description: "Document and develop components in isolation.",
        category: "design-systems",
        subcategory: "Tools",
        status: "locked",
        estimatedHours: 10,
        difficulty: "intermediate",
        skills: ["Stories", "Controls", "Addons"],
        resources: [
            { type: "video", title: "Storybook Tutorial", url: "#" },
        ],
        position: { x: 1600, y: 580 },
        tier: 2,
    },
    {
        id: "design-documentation",
        title: "Design Documentation",
        description: "Document components and usage guidelines.",
        category: "design-systems",
        subcategory: "Documentation",
        status: "locked",
        estimatedHours: 8,
        difficulty: "intermediate",
        skills: ["MDX", "Usage Docs", "Examples"],
        resources: [
            { type: "article", title: "Design System Docs", url: "#" },
        ],
        position: { x: 1600, y: 660 },
        tier: 2,
    },
    {
        id: "theming",
        title: "Theming Systems",
        description: "Implement theme switching and customization.",
        category: "design-systems",
        subcategory: "Theming",
        status: "locked",
        estimatedHours: 10,
        difficulty: "advanced",
        skills: ["Theme Provider", "Dark Mode", "Custom Themes"],
        resources: [
            { type: "video", title: "Theming Deep Dive", url: "#" },
        ],
        position: { x: 1450, y: 740 },
        tier: 3,
    },
    {
        id: "design-patterns",
        title: "UI Design Patterns",
        description: "Common patterns for navigation, forms, and feedback.",
        category: "design-systems",
        subcategory: "Patterns",
        status: "locked",
        estimatedHours: 10,
        difficulty: "intermediate",
        skills: ["Navigation", "Forms", "Feedback"],
        resources: [
            { type: "article", title: "UI Pattern Library", url: "#" },
        ],
        position: { x: 1600, y: 740 },
        tier: 2,
    },
    {
        id: "atomic-design",
        title: "Atomic Design",
        description: "Organize components with atomic methodology.",
        category: "design-systems",
        subcategory: "Methodology",
        status: "locked",
        estimatedHours: 6,
        difficulty: "intermediate",
        skills: ["Atoms", "Molecules", "Organisms"],
        resources: [
            { type: "article", title: "Atomic Design Guide", url: "#" },
        ],
        position: { x: 1525, y: 820 },
        tier: 2,
    },
    {
        id: "ui-frameworks",
        title: "UI Frameworks",
        description: "Evaluate and use Shadcn, Radix, and Headless UI.",
        category: "design-systems",
        subcategory: "Frameworks",
        status: "locked",
        estimatedHours: 10,
        difficulty: "intermediate",
        skills: ["Shadcn/ui", "Radix", "Headless UI"],
        resources: [
            { type: "video", title: "Comparing UI Libraries", url: "#" },
        ],
        position: { x: 1675, y: 820 },
        tier: 2,
    },
];
