/**
 * HTML & CSS Curriculum Nodes (12 nodes)
 * Foundation of web development - markup and styling fundamentals
 */

import { CurriculumNode } from "../curriculumTypes";

export const htmlCssNodes: CurriculumNode[] = [
    {
        id: "html-basics",
        title: "HTML Basics",
        description: "Learn the fundamental building blocks of web pages including elements, attributes, and document structure.",
        category: "html-css",
        subcategory: "HTML",
        status: "completed",
        estimatedHours: 8,
        difficulty: "beginner",
        skills: ["HTML5", "Elements", "Attributes"],
        resources: [
            { type: "article", title: "MDN HTML Basics", url: "#" },
            { type: "video", title: "HTML Crash Course", url: "#" },
        ],
        position: { x: 100, y: 80 },
        tier: 0,
    },
    {
        id: "semantic-html",
        title: "Semantic HTML",
        description: "Use meaningful HTML elements to improve accessibility and SEO.",
        category: "html-css",
        subcategory: "HTML",
        status: "completed",
        estimatedHours: 6,
        difficulty: "beginner",
        skills: ["Semantic Tags", "Document Outline", "SEO"],
        resources: [
            { type: "article", title: "Semantic HTML Guide", url: "#" },
        ],
        position: { x: 100, y: 160 },
        tier: 0,
    },
    {
        id: "html-forms",
        title: "HTML Forms",
        description: "Create interactive forms with validation and accessibility features.",
        category: "html-css",
        subcategory: "HTML",
        status: "completed",
        estimatedHours: 8,
        difficulty: "beginner",
        skills: ["Form Elements", "Validation", "Input Types"],
        resources: [
            { type: "practice", title: "Form Building Exercises" },
        ],
        position: { x: 100, y: 240 },
        tier: 0,
    },
    {
        id: "css-basics",
        title: "CSS Basics",
        description: "Learn selectors, properties, and the cascade for styling web pages.",
        category: "html-css",
        subcategory: "CSS",
        status: "completed",
        estimatedHours: 10,
        difficulty: "beginner",
        skills: ["Selectors", "Box Model", "Specificity"],
        resources: [
            { type: "article", title: "CSS Fundamentals", url: "#" },
            { type: "video", title: "CSS Complete Guide", url: "#" },
        ],
        position: { x: 250, y: 80 },
        tier: 0,
    },
    {
        id: "flexbox",
        title: "Flexbox Layout",
        description: "Master one-dimensional layouts with flexible box model.",
        category: "html-css",
        subcategory: "CSS",
        status: "completed",
        estimatedHours: 8,
        difficulty: "beginner",
        skills: ["Flex Container", "Flex Items", "Alignment"],
        resources: [
            { type: "practice", title: "Flexbox Froggy" },
            { type: "article", title: "Complete Guide to Flexbox", url: "#" },
        ],
        position: { x: 250, y: 160 },
        tier: 1,
    },
    {
        id: "css-grid",
        title: "CSS Grid",
        description: "Create two-dimensional layouts with powerful grid system.",
        category: "html-css",
        subcategory: "CSS",
        status: "completed",
        estimatedHours: 10,
        difficulty: "intermediate",
        skills: ["Grid Container", "Grid Lines", "Areas"],
        resources: [
            { type: "practice", title: "Grid Garden" },
            { type: "video", title: "CSS Grid Course", url: "#" },
        ],
        position: { x: 250, y: 240 },
        tier: 1,
    },
    {
        id: "responsive-design",
        title: "Responsive Design",
        description: "Build websites that work on all screen sizes with media queries.",
        category: "html-css",
        subcategory: "CSS",
        status: "in_progress",
        estimatedHours: 12,
        difficulty: "intermediate",
        skills: ["Media Queries", "Mobile First", "Breakpoints"],
        resources: [
            { type: "article", title: "Responsive Web Design", url: "#" },
        ],
        position: { x: 250, y: 320 },
        tier: 1,
    },
    {
        id: "css-animations",
        title: "CSS Animations",
        description: "Add motion and interactivity with transitions and keyframe animations.",
        category: "html-css",
        subcategory: "CSS",
        status: "available",
        estimatedHours: 8,
        difficulty: "intermediate",
        skills: ["Transitions", "Keyframes", "Transform"],
        resources: [
            { type: "video", title: "Animation Masterclass", url: "#" },
        ],
        position: { x: 400, y: 160 },
        tier: 2,
    },
    {
        id: "css-variables",
        title: "CSS Custom Properties",
        description: "Use CSS variables for maintainable and themeable stylesheets.",
        category: "html-css",
        subcategory: "CSS",
        status: "available",
        estimatedHours: 4,
        difficulty: "intermediate",
        skills: ["Custom Properties", "Theming", "Dark Mode"],
        resources: [
            { type: "article", title: "CSS Variables Guide", url: "#" },
        ],
        position: { x: 400, y: 240 },
        tier: 2,
    },
    {
        id: "css-architecture",
        title: "CSS Architecture",
        description: "Organize CSS at scale with methodologies like BEM and OOCSS.",
        category: "html-css",
        subcategory: "CSS",
        status: "available",
        estimatedHours: 6,
        difficulty: "intermediate",
        skills: ["BEM", "OOCSS", "SMACSS"],
        resources: [
            { type: "article", title: "CSS Architecture Patterns", url: "#" },
        ],
        position: { x: 400, y: 320 },
        tier: 2,
    },
    {
        id: "sass-preprocessor",
        title: "Sass/SCSS",
        description: "Extend CSS with variables, nesting, mixins, and functions.",
        category: "html-css",
        subcategory: "CSS",
        status: "locked",
        estimatedHours: 8,
        difficulty: "intermediate",
        skills: ["Sass", "Mixins", "Functions"],
        resources: [
            { type: "course", title: "Sass Complete Course", url: "#" },
        ],
        position: { x: 550, y: 240 },
        tier: 2,
    },
    {
        id: "tailwind-css",
        title: "Tailwind CSS",
        description: "Build designs rapidly with utility-first CSS framework.",
        category: "html-css",
        subcategory: "CSS",
        status: "locked",
        estimatedHours: 12,
        difficulty: "intermediate",
        skills: ["Utility Classes", "Configuration", "Plugins"],
        resources: [
            { type: "video", title: "Tailwind CSS Tutorial", url: "#" },
        ],
        position: { x: 550, y: 320 },
        tier: 2,
    },
];
