/**
 * JavaScript Core Curriculum Nodes (15 nodes)
 * Core programming language fundamentals and browser APIs
 */

import { CurriculumNode } from "../curriculumTypes";

export const javascriptNodes: CurriculumNode[] = [
    {
        id: "js-fundamentals",
        title: "JavaScript Fundamentals",
        description: "Variables, data types, operators, and control flow basics.",
        category: "javascript",
        subcategory: "Core",
        status: "completed",
        estimatedHours: 15,
        difficulty: "beginner",
        skills: ["Variables", "Data Types", "Control Flow"],
        resources: [
            { type: "course", title: "JavaScript.info", url: "#" },
            { type: "video", title: "JS Crash Course", url: "#" },
        ],
        position: { x: 700, y: 80 },
        tier: 0,
    },
    {
        id: "js-functions",
        title: "Functions & Scope",
        description: "Function declarations, expressions, closures, and scope chains.",
        category: "javascript",
        subcategory: "Core",
        status: "completed",
        estimatedHours: 12,
        difficulty: "beginner",
        skills: ["Functions", "Closures", "Hoisting"],
        resources: [
            { type: "article", title: "Understanding Functions", url: "#" },
        ],
        position: { x: 700, y: 160 },
        tier: 1,
    },
    {
        id: "js-objects-arrays",
        title: "Objects & Arrays",
        description: "Work with complex data structures and their methods.",
        category: "javascript",
        subcategory: "Core",
        status: "completed",
        estimatedHours: 12,
        difficulty: "beginner",
        skills: ["Objects", "Arrays", "Destructuring"],
        resources: [
            { type: "practice", title: "Array Method Exercises" },
        ],
        position: { x: 700, y: 240 },
        tier: 1,
    },
    {
        id: "dom-manipulation",
        title: "DOM Manipulation",
        description: "Select, modify, and create HTML elements with JavaScript.",
        category: "javascript",
        subcategory: "Browser",
        status: "completed",
        estimatedHours: 10,
        difficulty: "beginner",
        skills: ["querySelector", "createElement", "Events"],
        resources: [
            { type: "video", title: "DOM Manipulation Guide", url: "#" },
        ],
        position: { x: 850, y: 160 },
        tier: 1,
    },
    {
        id: "js-events",
        title: "Event Handling",
        description: "Handle user interactions with event listeners and delegation.",
        category: "javascript",
        subcategory: "Browser",
        status: "completed",
        estimatedHours: 8,
        difficulty: "intermediate",
        skills: ["Event Listeners", "Bubbling", "Delegation"],
        resources: [
            { type: "article", title: "Event Handling Deep Dive", url: "#" },
        ],
        position: { x: 850, y: 240 },
        tier: 1,
    },
    {
        id: "es6-features",
        title: "ES6+ Features",
        description: "Modern JavaScript features: arrow functions, spread, template literals.",
        category: "javascript",
        subcategory: "Core",
        status: "in_progress",
        estimatedHours: 12,
        difficulty: "intermediate",
        skills: ["Arrow Functions", "Spread/Rest", "Modules"],
        resources: [
            { type: "course", title: "ES6 Complete Guide", url: "#" },
        ],
        position: { x: 700, y: 320 },
        tier: 1,
    },
    {
        id: "async-javascript",
        title: "Async JavaScript",
        description: "Callbacks, promises, and async/await for asynchronous operations.",
        category: "javascript",
        subcategory: "Core",
        status: "available",
        estimatedHours: 15,
        difficulty: "intermediate",
        skills: ["Promises", "async/await", "Event Loop"],
        resources: [
            { type: "video", title: "Async JS Masterclass", url: "#" },
        ],
        position: { x: 700, y: 400 },
        tier: 2,
    },
    {
        id: "fetch-api",
        title: "Fetch API & HTTP",
        description: "Make HTTP requests and handle API responses.",
        category: "javascript",
        subcategory: "Browser",
        status: "available",
        estimatedHours: 8,
        difficulty: "intermediate",
        skills: ["Fetch", "REST APIs", "JSON"],
        resources: [
            { type: "article", title: "Fetch API Guide", url: "#" },
        ],
        position: { x: 850, y: 400 },
        tier: 2,
    },
    {
        id: "js-modules",
        title: "JavaScript Modules",
        description: "Organize code with ES modules and module bundlers.",
        category: "javascript",
        subcategory: "Core",
        status: "available",
        estimatedHours: 6,
        difficulty: "intermediate",
        skills: ["import/export", "Module Patterns", "Bundling"],
        resources: [
            { type: "article", title: "JavaScript Modules", url: "#" },
        ],
        position: { x: 700, y: 480 },
        tier: 2,
    },
    {
        id: "error-handling",
        title: "Error Handling",
        description: "Handle errors gracefully with try/catch and custom errors.",
        category: "javascript",
        subcategory: "Core",
        status: "locked",
        estimatedHours: 6,
        difficulty: "intermediate",
        skills: ["try/catch", "Custom Errors", "Error Boundaries"],
        resources: [
            { type: "article", title: "Error Handling Patterns", url: "#" },
        ],
        position: { x: 850, y: 480 },
        tier: 2,
    },
    {
        id: "js-classes",
        title: "Classes & OOP",
        description: "Object-oriented programming with ES6 classes.",
        category: "javascript",
        subcategory: "Core",
        status: "locked",
        estimatedHours: 10,
        difficulty: "intermediate",
        skills: ["Classes", "Inheritance", "Encapsulation"],
        resources: [
            { type: "video", title: "OOP in JavaScript", url: "#" },
        ],
        position: { x: 700, y: 560 },
        tier: 2,
    },
    {
        id: "web-storage",
        title: "Web Storage APIs",
        description: "Store data locally with localStorage, sessionStorage, and IndexedDB.",
        category: "javascript",
        subcategory: "Browser",
        status: "locked",
        estimatedHours: 6,
        difficulty: "intermediate",
        skills: ["localStorage", "sessionStorage", "IndexedDB"],
        resources: [
            { type: "article", title: "Web Storage Guide", url: "#" },
        ],
        position: { x: 850, y: 560 },
        tier: 2,
    },
    {
        id: "regex",
        title: "Regular Expressions",
        description: "Pattern matching and text manipulation with regex.",
        category: "javascript",
        subcategory: "Core",
        status: "locked",
        estimatedHours: 8,
        difficulty: "advanced",
        skills: ["Patterns", "Groups", "Lookahead"],
        resources: [
            { type: "practice", title: "Regex Exercises" },
        ],
        position: { x: 700, y: 640 },
        tier: 3,
    },
    {
        id: "web-apis",
        title: "Browser APIs",
        description: "Geolocation, Notifications, Clipboard, and other Web APIs.",
        category: "javascript",
        subcategory: "Browser",
        status: "locked",
        estimatedHours: 10,
        difficulty: "advanced",
        skills: ["Geolocation", "Notifications", "Web Workers"],
        resources: [
            { type: "article", title: "Modern Web APIs", url: "#" },
        ],
        position: { x: 850, y: 640 },
        tier: 3,
    },
    {
        id: "functional-js",
        title: "Functional JavaScript",
        description: "Functional programming patterns: map, filter, reduce, composition.",
        category: "javascript",
        subcategory: "Core",
        status: "locked",
        estimatedHours: 12,
        difficulty: "advanced",
        skills: ["Pure Functions", "Immutability", "Composition"],
        resources: [
            { type: "course", title: "Functional JS Guide", url: "#" },
        ],
        position: { x: 775, y: 720 },
        tier: 3,
    },
];
