/**
 * Performance Curriculum Nodes (8 nodes)
 * Web performance optimization techniques
 */

import { CurriculumNode } from "../curriculumTypes";

export const performanceNodes: CurriculumNode[] = [
    {
        id: "web-vitals",
        title: "Core Web Vitals",
        description: "Measure and optimize LCP, FID, and CLS.",
        category: "performance",
        subcategory: "Metrics",
        status: "locked",
        estimatedHours: 8,
        difficulty: "intermediate",
        skills: ["LCP", "FID", "CLS"],
        resources: [
            { type: "article", title: "Web Vitals Guide", url: "#" },
        ],
        position: { x: 850, y: 500 },
        tier: 2,
    },
    {
        id: "lighthouse",
        title: "Lighthouse & DevTools",
        description: "Profile and audit web performance.",
        category: "performance",
        subcategory: "Tools",
        status: "locked",
        estimatedHours: 6,
        difficulty: "intermediate",
        skills: ["Lighthouse", "Performance Tab", "Audits"],
        resources: [
            { type: "video", title: "Chrome DevTools Performance", url: "#" },
        ],
        position: { x: 850, y: 580 },
        tier: 2,
    },
    {
        id: "lazy-loading",
        title: "Lazy Loading",
        description: "Defer loading of images and components.",
        category: "performance",
        subcategory: "Techniques",
        status: "locked",
        estimatedHours: 6,
        difficulty: "intermediate",
        skills: ["Image Lazy Loading", "Route Splitting", "Dynamic Import"],
        resources: [
            { type: "article", title: "Lazy Loading Patterns", url: "#" },
        ],
        position: { x: 850, y: 660 },
        tier: 2,
    },
    {
        id: "caching",
        title: "Caching Strategies",
        description: "Browser caching, CDNs, and service workers.",
        category: "performance",
        subcategory: "Caching",
        status: "locked",
        estimatedHours: 10,
        difficulty: "advanced",
        skills: ["Cache-Control", "CDN", "Service Workers"],
        resources: [
            { type: "course", title: "Web Caching Deep Dive", url: "#" },
        ],
        position: { x: 1000, y: 580 },
        tier: 3,
    },
    {
        id: "image-optimization",
        title: "Image Optimization",
        description: "Formats, compression, and responsive images.",
        category: "performance",
        subcategory: "Assets",
        status: "locked",
        estimatedHours: 6,
        difficulty: "intermediate",
        skills: ["WebP", "AVIF", "srcset"],
        resources: [
            { type: "article", title: "Image Optimization Guide", url: "#" },
        ],
        position: { x: 1000, y: 660 },
        tier: 2,
    },
    {
        id: "bundle-analysis",
        title: "Bundle Analysis",
        description: "Analyze and reduce bundle sizes.",
        category: "performance",
        subcategory: "Bundling",
        status: "locked",
        estimatedHours: 6,
        difficulty: "advanced",
        skills: ["Bundle Analyzer", "Tree Shaking", "Code Splitting"],
        resources: [
            { type: "video", title: "Bundle Optimization", url: "#" },
        ],
        position: { x: 850, y: 740 },
        tier: 3,
    },
    {
        id: "runtime-performance",
        title: "Runtime Performance",
        description: "Optimize JavaScript execution and rendering.",
        category: "performance",
        subcategory: "Runtime",
        status: "locked",
        estimatedHours: 12,
        difficulty: "advanced",
        skills: ["Profiling", "Memory Leaks", "Reflows"],
        resources: [
            { type: "course", title: "JavaScript Performance", url: "#" },
        ],
        position: { x: 1000, y: 740 },
        tier: 3,
    },
    {
        id: "performance-monitoring",
        title: "Performance Monitoring",
        description: "Real user monitoring and analytics.",
        category: "performance",
        subcategory: "Monitoring",
        status: "locked",
        estimatedHours: 8,
        difficulty: "advanced",
        skills: ["RUM", "Analytics", "Alerts"],
        resources: [
            { type: "article", title: "Performance Monitoring Setup", url: "#" },
        ],
        position: { x: 925, y: 820 },
        tier: 3,
    },
];
