/**
 * React Ecosystem Curriculum Nodes (18 nodes)
 * Component-based UI library and its ecosystem
 */

import { CurriculumNode } from "../curriculumTypes";

export const reactNodes: CurriculumNode[] = [
    {
        id: "react-fundamentals",
        title: "React Fundamentals",
        description: "Components, JSX, and the React rendering model.",
        category: "react",
        subcategory: "Core",
        status: "available",
        estimatedHours: 15,
        difficulty: "intermediate",
        skills: ["Components", "JSX", "Virtual DOM"],
        resources: [
            { type: "course", title: "React Documentation", url: "#" },
            { type: "video", title: "React Complete Guide", url: "#" },
        ],
        position: { x: 1350, y: 80 },
        tier: 2,
    },
    {
        id: "react-props-state",
        title: "Props & State",
        description: "Pass data and manage component state effectively.",
        category: "react",
        subcategory: "Core",
        status: "locked",
        estimatedHours: 10,
        difficulty: "intermediate",
        skills: ["Props", "State", "Lifting State"],
        resources: [
            { type: "article", title: "State Management Basics", url: "#" },
        ],
        position: { x: 1350, y: 160 },
        tier: 2,
    },
    {
        id: "react-hooks-basics",
        title: "React Hooks Basics",
        description: "useState, useEffect, and the rules of hooks.",
        category: "react",
        subcategory: "Hooks",
        status: "locked",
        estimatedHours: 12,
        difficulty: "intermediate",
        skills: ["useState", "useEffect", "Rules of Hooks"],
        resources: [
            { type: "video", title: "React Hooks Tutorial", url: "#" },
        ],
        position: { x: 1350, y: 240 },
        tier: 2,
    },
    {
        id: "react-advanced-hooks",
        title: "Advanced Hooks",
        description: "useReducer, useCallback, useMemo, and useRef.",
        category: "react",
        subcategory: "Hooks",
        status: "locked",
        estimatedHours: 10,
        difficulty: "advanced",
        skills: ["useReducer", "useCallback", "useMemo"],
        resources: [
            { type: "article", title: "Advanced Hooks Patterns", url: "#" },
        ],
        position: { x: 1350, y: 320 },
        tier: 3,
    },
    {
        id: "react-custom-hooks",
        title: "Custom Hooks",
        description: "Extract and reuse stateful logic with custom hooks.",
        category: "react",
        subcategory: "Hooks",
        status: "locked",
        estimatedHours: 8,
        difficulty: "advanced",
        skills: ["Custom Hooks", "Logic Reuse", "Composition"],
        resources: [
            { type: "practice", title: "Custom Hook Exercises" },
        ],
        position: { x: 1350, y: 400 },
        tier: 3,
    },
    {
        id: "react-context",
        title: "Context API",
        description: "Share state globally without prop drilling.",
        category: "react",
        subcategory: "State",
        status: "locked",
        estimatedHours: 8,
        difficulty: "intermediate",
        skills: ["Context", "Provider", "Consumer"],
        resources: [
            { type: "video", title: "React Context Guide", url: "#" },
        ],
        position: { x: 1500, y: 240 },
        tier: 2,
    },
    {
        id: "react-router",
        title: "React Router",
        description: "Add navigation and routing to React applications.",
        category: "react",
        subcategory: "Routing",
        status: "locked",
        estimatedHours: 10,
        difficulty: "intermediate",
        skills: ["Routes", "Navigation", "Dynamic Routes"],
        resources: [
            { type: "course", title: "React Router Tutorial", url: "#" },
        ],
        position: { x: 1500, y: 160 },
        tier: 2,
    },
    {
        id: "react-forms",
        title: "Forms in React",
        description: "Controlled components, form validation, and libraries.",
        category: "react",
        subcategory: "Forms",
        status: "locked",
        estimatedHours: 10,
        difficulty: "intermediate",
        skills: ["Controlled Forms", "Validation", "React Hook Form"],
        resources: [
            { type: "article", title: "React Forms Guide", url: "#" },
        ],
        position: { x: 1500, y: 320 },
        tier: 2,
    },
    {
        id: "react-styling",
        title: "Styling React",
        description: "CSS Modules, Styled Components, and CSS-in-JS.",
        category: "react",
        subcategory: "Styling",
        status: "locked",
        estimatedHours: 8,
        difficulty: "intermediate",
        skills: ["CSS Modules", "Styled Components", "Emotion"],
        resources: [
            { type: "video", title: "CSS-in-JS Comparison", url: "#" },
        ],
        position: { x: 1650, y: 160 },
        tier: 2,
    },
    {
        id: "react-performance",
        title: "React Performance",
        description: "Optimize renders with memoization and code splitting.",
        category: "react",
        subcategory: "Performance",
        status: "locked",
        estimatedHours: 12,
        difficulty: "advanced",
        skills: ["memo", "Profiler", "Code Splitting"],
        resources: [
            { type: "article", title: "React Performance Guide", url: "#" },
        ],
        position: { x: 1500, y: 400 },
        tier: 3,
    },
    {
        id: "react-suspense",
        title: "Suspense & Lazy",
        description: "Code splitting and loading states with Suspense.",
        category: "react",
        subcategory: "Performance",
        status: "locked",
        estimatedHours: 6,
        difficulty: "advanced",
        skills: ["Suspense", "lazy()", "Error Boundaries"],
        resources: [
            { type: "video", title: "React Suspense Deep Dive", url: "#" },
        ],
        position: { x: 1350, y: 480 },
        tier: 3,
    },
    {
        id: "react-server-components",
        title: "React Server Components",
        description: "Server-side rendering with React Server Components.",
        category: "react",
        subcategory: "Advanced",
        status: "locked",
        estimatedHours: 10,
        difficulty: "expert",
        skills: ["RSC", "Server/Client", "Streaming"],
        resources: [
            { type: "article", title: "Understanding RSC", url: "#" },
        ],
        position: { x: 1350, y: 560 },
        tier: 4,
    },
    {
        id: "react-patterns",
        title: "React Patterns",
        description: "Compound components, render props, and HOCs.",
        category: "react",
        subcategory: "Patterns",
        status: "locked",
        estimatedHours: 12,
        difficulty: "advanced",
        skills: ["Compound", "Render Props", "HOC"],
        resources: [
            { type: "course", title: "Advanced React Patterns", url: "#" },
        ],
        position: { x: 1650, y: 320 },
        tier: 3,
    },
    {
        id: "react-testing",
        title: "Testing React",
        description: "Unit and integration testing with React Testing Library.",
        category: "react",
        subcategory: "Testing",
        status: "locked",
        estimatedHours: 15,
        difficulty: "advanced",
        skills: ["RTL", "Jest", "User Events"],
        resources: [
            { type: "video", title: "React Testing Complete", url: "#" },
        ],
        position: { x: 1650, y: 400 },
        tier: 3,
    },
    {
        id: "react-query",
        title: "React Query",
        description: "Data fetching and caching with TanStack Query.",
        category: "react",
        subcategory: "Data",
        status: "locked",
        estimatedHours: 12,
        difficulty: "advanced",
        skills: ["Queries", "Mutations", "Caching"],
        resources: [
            { type: "course", title: "React Query Essentials", url: "#" },
        ],
        position: { x: 1500, y: 480 },
        tier: 3,
    },
    {
        id: "nextjs-basics",
        title: "Next.js Basics",
        description: "File-based routing and pages in Next.js.",
        category: "react",
        subcategory: "Next.js",
        status: "locked",
        estimatedHours: 15,
        difficulty: "advanced",
        skills: ["Pages Router", "API Routes", "Static Generation"],
        resources: [
            { type: "course", title: "Next.js Documentation", url: "#" },
        ],
        position: { x: 1500, y: 560 },
        tier: 3,
    },
    {
        id: "nextjs-app-router",
        title: "Next.js App Router",
        description: "Modern Next.js with App Router and Server Components.",
        category: "react",
        subcategory: "Next.js",
        status: "locked",
        estimatedHours: 20,
        difficulty: "expert",
        skills: ["App Router", "Server Actions", "Streaming"],
        resources: [
            { type: "video", title: "App Router Deep Dive", url: "#" },
        ],
        position: { x: 1500, y: 640 },
        tier: 4,
    },
    {
        id: "react-state-libs",
        title: "State Libraries",
        description: "Zustand, Jotai, and modern state management.",
        category: "react",
        subcategory: "State",
        status: "locked",
        estimatedHours: 10,
        difficulty: "advanced",
        skills: ["Zustand", "Jotai", "Recoil"],
        resources: [
            { type: "article", title: "State Library Comparison", url: "#" },
        ],
        position: { x: 1650, y: 480 },
        tier: 3,
    },
];
