/**
 * State Management Curriculum Nodes (10 nodes)
 * Managing application state at scale
 */

import { CurriculumNode } from "../curriculumTypes";

export const stateManagementNodes: CurriculumNode[] = [
    {
        id: "state-concepts",
        title: "State Management Concepts",
        description: "Local vs global state, derived state, and state machines.",
        category: "state-management",
        subcategory: "Concepts",
        status: "locked",
        estimatedHours: 6,
        difficulty: "intermediate",
        skills: ["Local State", "Global State", "Derived State"],
        resources: [
            { type: "article", title: "State Management Patterns", url: "#" },
        ],
        position: { x: 1850, y: 580 },
        tier: 2,
    },
    {
        id: "context-api",
        title: "React Context Deep Dive",
        description: "Advanced patterns with React Context.",
        category: "state-management",
        subcategory: "React",
        status: "locked",
        estimatedHours: 8,
        difficulty: "intermediate",
        skills: ["Context Split", "Selectors", "Optimization"],
        resources: [
            { type: "video", title: "Context API Mastery", url: "#" },
        ],
        position: { x: 1850, y: 660 },
        tier: 2,
    },
    {
        id: "redux-basics",
        title: "Redux Fundamentals",
        description: "Actions, reducers, and the Redux store.",
        category: "state-management",
        subcategory: "Redux",
        status: "locked",
        estimatedHours: 12,
        difficulty: "intermediate",
        skills: ["Actions", "Reducers", "Store"],
        resources: [
            { type: "course", title: "Redux Essentials", url: "#" },
        ],
        position: { x: 2000, y: 580 },
        tier: 2,
    },
    {
        id: "redux-toolkit",
        title: "Redux Toolkit",
        description: "Modern Redux with RTK and createSlice.",
        category: "state-management",
        subcategory: "Redux",
        status: "locked",
        estimatedHours: 10,
        difficulty: "advanced",
        skills: ["createSlice", "RTK Query", "Thunks"],
        resources: [
            { type: "video", title: "Redux Toolkit Guide", url: "#" },
        ],
        position: { x: 2000, y: 660 },
        tier: 3,
    },
    {
        id: "zustand",
        title: "Zustand",
        description: "Simple, unopinionated state management.",
        category: "state-management",
        subcategory: "Libraries",
        status: "locked",
        estimatedHours: 6,
        difficulty: "intermediate",
        skills: ["Stores", "Subscriptions", "Middleware"],
        resources: [
            { type: "article", title: "Zustand Documentation", url: "#" },
        ],
        position: { x: 1850, y: 740 },
        tier: 2,
    },
    {
        id: "jotai",
        title: "Jotai",
        description: "Atomic state management for React.",
        category: "state-management",
        subcategory: "Libraries",
        status: "locked",
        estimatedHours: 6,
        difficulty: "intermediate",
        skills: ["Atoms", "Derived Atoms", "Async"],
        resources: [
            { type: "video", title: "Jotai Tutorial", url: "#" },
        ],
        position: { x: 2000, y: 740 },
        tier: 2,
    },
    {
        id: "recoil",
        title: "Recoil",
        description: "Facebook's state management library.",
        category: "state-management",
        subcategory: "Libraries",
        status: "locked",
        estimatedHours: 8,
        difficulty: "intermediate",
        skills: ["Atoms", "Selectors", "Async Queries"],
        resources: [
            { type: "article", title: "Recoil Guide", url: "#" },
        ],
        position: { x: 2150, y: 660 },
        tier: 2,
    },
    {
        id: "mobx",
        title: "MobX",
        description: "Simple, scalable state management with observables.",
        category: "state-management",
        subcategory: "Libraries",
        status: "locked",
        estimatedHours: 10,
        difficulty: "advanced",
        skills: ["Observables", "Actions", "Computed"],
        resources: [
            { type: "course", title: "MobX in Depth", url: "#" },
        ],
        position: { x: 2150, y: 740 },
        tier: 3,
    },
    {
        id: "xstate",
        title: "XState",
        description: "State machines and statecharts for complex logic.",
        category: "state-management",
        subcategory: "Machines",
        status: "locked",
        estimatedHours: 15,
        difficulty: "advanced",
        skills: ["State Machines", "Statecharts", "Actors"],
        resources: [
            { type: "video", title: "XState Complete Course", url: "#" },
        ],
        position: { x: 1925, y: 820 },
        tier: 3,
    },
    {
        id: "state-patterns",
        title: "Advanced State Patterns",
        description: "Command, undo/redo, and optimistic updates.",
        category: "state-management",
        subcategory: "Patterns",
        status: "locked",
        estimatedHours: 12,
        difficulty: "expert",
        skills: ["Command Pattern", "Undo/Redo", "Optimistic UI"],
        resources: [
            { type: "article", title: "Advanced State Patterns", url: "#" },
        ],
        position: { x: 2075, y: 820 },
        tier: 4,
    },
];
