/**
 * Testing Curriculum Nodes (10 nodes)
 * Quality assurance through automated testing
 */

import { CurriculumNode } from "../curriculumTypes";

export const testingNodes: CurriculumNode[] = [
    {
        id: "testing-fundamentals",
        title: "Testing Fundamentals",
        description: "Test types, testing pyramid, and best practices.",
        category: "testing",
        subcategory: "Concepts",
        status: "available",
        estimatedHours: 6,
        difficulty: "intermediate",
        skills: ["Unit Tests", "Integration", "E2E"],
        resources: [
            { type: "article", title: "Testing Best Practices", url: "#" },
        ],
        position: { x: 100, y: 500 },
        tier: 2,
    },
    {
        id: "jest",
        title: "Jest Testing",
        description: "JavaScript testing framework with assertions and mocking.",
        category: "testing",
        subcategory: "Frameworks",
        status: "locked",
        estimatedHours: 12,
        difficulty: "intermediate",
        skills: ["Assertions", "Mocking", "Snapshots"],
        resources: [
            { type: "course", title: "Jest Complete Guide", url: "#" },
        ],
        position: { x: 100, y: 580 },
        tier: 2,
    },
    {
        id: "vitest",
        title: "Vitest",
        description: "Fast unit testing for Vite-based projects.",
        category: "testing",
        subcategory: "Frameworks",
        status: "locked",
        estimatedHours: 8,
        difficulty: "intermediate",
        skills: ["Vite Integration", "Coverage", "Benchmarks"],
        resources: [
            { type: "video", title: "Vitest Tutorial", url: "#" },
        ],
        position: { x: 250, y: 500 },
        tier: 2,
    },
    {
        id: "react-testing-library",
        title: "React Testing Library",
        description: "Test React components the way users interact.",
        category: "testing",
        subcategory: "Libraries",
        status: "locked",
        estimatedHours: 10,
        difficulty: "intermediate",
        skills: ["Queries", "User Events", "Async Testing"],
        resources: [
            { type: "article", title: "RTL Best Practices", url: "#" },
        ],
        position: { x: 250, y: 580 },
        tier: 2,
    },
    {
        id: "cypress",
        title: "Cypress E2E Testing",
        description: "End-to-end testing with Cypress.",
        category: "testing",
        subcategory: "E2E",
        status: "locked",
        estimatedHours: 12,
        difficulty: "intermediate",
        skills: ["Commands", "Fixtures", "Network"],
        resources: [
            { type: "course", title: "Cypress Complete Course", url: "#" },
        ],
        position: { x: 100, y: 660 },
        tier: 2,
    },
    {
        id: "playwright",
        title: "Playwright Testing",
        description: "Cross-browser E2E testing by Microsoft.",
        category: "testing",
        subcategory: "E2E",
        status: "locked",
        estimatedHours: 10,
        difficulty: "intermediate",
        skills: ["Multi-browser", "Codegen", "Trace Viewer"],
        resources: [
            { type: "video", title: "Playwright Tutorial", url: "#" },
        ],
        position: { x: 250, y: 660 },
        tier: 2,
    },
    {
        id: "tdd",
        title: "Test-Driven Development",
        description: "Write tests first to drive design and development.",
        category: "testing",
        subcategory: "Practices",
        status: "locked",
        estimatedHours: 10,
        difficulty: "advanced",
        skills: ["Red-Green-Refactor", "Test Design", "Refactoring"],
        resources: [
            { type: "article", title: "TDD Explained", url: "#" },
        ],
        position: { x: 400, y: 500 },
        tier: 3,
    },
    {
        id: "mocking-strategies",
        title: "Mocking Strategies",
        description: "Mock APIs, modules, and dependencies effectively.",
        category: "testing",
        subcategory: "Techniques",
        status: "locked",
        estimatedHours: 8,
        difficulty: "advanced",
        skills: ["MSW", "Jest Mocks", "Stubs"],
        resources: [
            { type: "video", title: "Mocking Deep Dive", url: "#" },
        ],
        position: { x: 400, y: 580 },
        tier: 3,
    },
    {
        id: "test-coverage",
        title: "Test Coverage",
        description: "Measure and improve test coverage meaningfully.",
        category: "testing",
        subcategory: "Metrics",
        status: "locked",
        estimatedHours: 4,
        difficulty: "intermediate",
        skills: ["Istanbul", "Coverage Reports", "Thresholds"],
        resources: [
            { type: "article", title: "Coverage Best Practices", url: "#" },
        ],
        position: { x: 400, y: 660 },
        tier: 2,
    },
    {
        id: "visual-testing",
        title: "Visual Regression Testing",
        description: "Catch visual bugs with screenshot testing.",
        category: "testing",
        subcategory: "Visual",
        status: "locked",
        estimatedHours: 6,
        difficulty: "advanced",
        skills: ["Percy", "Chromatic", "Storybook"],
        resources: [
            { type: "article", title: "Visual Testing Guide", url: "#" },
        ],
        position: { x: 325, y: 740 },
        tier: 3,
    },
];
