/**
 * TypeScript Curriculum Nodes (8 nodes)
 * Type-safe JavaScript for scalable applications
 */

import { CurriculumNode } from "../curriculumTypes";

export const typescriptNodes: CurriculumNode[] = [
    {
        id: "ts-basics",
        title: "TypeScript Basics",
        description: "Type annotations, interfaces, and basic TypeScript setup.",
        category: "typescript",
        subcategory: "Core",
        status: "available",
        estimatedHours: 10,
        difficulty: "intermediate",
        skills: ["Types", "Interfaces", "Type Inference"],
        resources: [
            { type: "course", title: "TypeScript Handbook", url: "#" },
        ],
        position: { x: 1000, y: 200 },
        tier: 2,
    },
    {
        id: "ts-advanced-types",
        title: "Advanced Types",
        description: "Union types, intersection types, type guards, and discriminated unions.",
        category: "typescript",
        subcategory: "Core",
        status: "locked",
        estimatedHours: 12,
        difficulty: "intermediate",
        skills: ["Union Types", "Type Guards", "Narrowing"],
        resources: [
            { type: "article", title: "Advanced Types Guide", url: "#" },
        ],
        position: { x: 1000, y: 280 },
        tier: 2,
    },
    {
        id: "ts-generics",
        title: "Generics",
        description: "Create reusable type-safe components with generics.",
        category: "typescript",
        subcategory: "Core",
        status: "locked",
        estimatedHours: 10,
        difficulty: "advanced",
        skills: ["Generic Functions", "Constraints", "Inference"],
        resources: [
            { type: "video", title: "TypeScript Generics", url: "#" },
        ],
        position: { x: 1000, y: 360 },
        tier: 3,
    },
    {
        id: "ts-utility-types",
        title: "Utility Types",
        description: "Built-in utility types: Partial, Required, Pick, Omit, Record.",
        category: "typescript",
        subcategory: "Core",
        status: "locked",
        estimatedHours: 6,
        difficulty: "advanced",
        skills: ["Partial", "Pick", "Omit", "Record"],
        resources: [
            { type: "article", title: "Utility Types Reference", url: "#" },
        ],
        position: { x: 1000, y: 440 },
        tier: 3,
    },
    {
        id: "ts-decorators",
        title: "Decorators",
        description: "Add metadata and modify classes with decorators.",
        category: "typescript",
        subcategory: "Advanced",
        status: "locked",
        estimatedHours: 8,
        difficulty: "advanced",
        skills: ["Class Decorators", "Method Decorators", "Metadata"],
        resources: [
            { type: "article", title: "TypeScript Decorators", url: "#" },
        ],
        position: { x: 1150, y: 360 },
        tier: 3,
    },
    {
        id: "ts-config",
        title: "TypeScript Configuration",
        description: "Configure tsconfig.json for different project needs.",
        category: "typescript",
        subcategory: "Tooling",
        status: "locked",
        estimatedHours: 4,
        difficulty: "intermediate",
        skills: ["tsconfig", "Compiler Options", "Project References"],
        resources: [
            { type: "article", title: "TSConfig Reference", url: "#" },
        ],
        position: { x: 1150, y: 200 },
        tier: 2,
    },
    {
        id: "ts-declaration-files",
        title: "Declaration Files",
        description: "Create and use .d.ts files for type definitions.",
        category: "typescript",
        subcategory: "Tooling",
        status: "locked",
        estimatedHours: 6,
        difficulty: "advanced",
        skills: ["Declaration Files", "DefinitelyTyped", "Ambient"],
        resources: [
            { type: "article", title: "Declaration Files Guide", url: "#" },
        ],
        position: { x: 1150, y: 280 },
        tier: 3,
    },
    {
        id: "ts-strict-mode",
        title: "Strict TypeScript",
        description: "Enable strict mode and handle strictNullChecks properly.",
        category: "typescript",
        subcategory: "Advanced",
        status: "locked",
        estimatedHours: 8,
        difficulty: "advanced",
        skills: ["Strict Mode", "Null Checks", "Type Safety"],
        resources: [
            { type: "article", title: "Strict TypeScript", url: "#" },
        ],
        position: { x: 1150, y: 440 },
        tier: 3,
    },
];
