/**
 * Vue.js Curriculum Nodes (10 nodes)
 * Progressive JavaScript framework for building UIs
 */

import { CurriculumNode } from "../curriculumTypes";

export const vueNodes: CurriculumNode[] = [
    {
        id: "vue-fundamentals",
        title: "Vue.js Fundamentals",
        description: "Components, templates, and reactivity in Vue.",
        category: "vue",
        subcategory: "Core",
        status: "locked",
        estimatedHours: 15,
        difficulty: "intermediate",
        skills: ["Components", "Templates", "Reactivity"],
        resources: [
            { type: "course", title: "Vue.js Documentation", url: "#" },
        ],
        position: { x: 1850, y: 80 },
        tier: 2,
    },
    {
        id: "vue-composition-api",
        title: "Composition API",
        description: "Modern Vue with setup() and composables.",
        category: "vue",
        subcategory: "Core",
        status: "locked",
        estimatedHours: 12,
        difficulty: "intermediate",
        skills: ["setup()", "ref", "reactive", "Composables"],
        resources: [
            { type: "video", title: "Composition API Guide", url: "#" },
        ],
        position: { x: 1850, y: 160 },
        tier: 2,
    },
    {
        id: "vue-router",
        title: "Vue Router",
        description: "Navigation and routing in Vue applications.",
        category: "vue",
        subcategory: "Routing",
        status: "locked",
        estimatedHours: 8,
        difficulty: "intermediate",
        skills: ["Routes", "Guards", "Lazy Loading"],
        resources: [
            { type: "article", title: "Vue Router Guide", url: "#" },
        ],
        position: { x: 1850, y: 240 },
        tier: 2,
    },
    {
        id: "pinia",
        title: "Pinia State Management",
        description: "Modern state management for Vue 3.",
        category: "vue",
        subcategory: "State",
        status: "locked",
        estimatedHours: 8,
        difficulty: "intermediate",
        skills: ["Stores", "Actions", "Getters"],
        resources: [
            { type: "course", title: "Pinia Documentation", url: "#" },
        ],
        position: { x: 1850, y: 320 },
        tier: 2,
    },
    {
        id: "vue-testing",
        title: "Testing Vue",
        description: "Unit testing Vue components with Vitest.",
        category: "vue",
        subcategory: "Testing",
        status: "locked",
        estimatedHours: 10,
        difficulty: "advanced",
        skills: ["Vitest", "Vue Test Utils", "Mounting"],
        resources: [
            { type: "video", title: "Vue Testing Guide", url: "#" },
        ],
        position: { x: 1850, y: 400 },
        tier: 3,
    },
    {
        id: "nuxt-basics",
        title: "Nuxt.js Basics",
        description: "Full-stack Vue framework with SSR.",
        category: "vue",
        subcategory: "Nuxt",
        status: "locked",
        estimatedHours: 15,
        difficulty: "advanced",
        skills: ["Pages", "Server Routes", "Auto-imports"],
        resources: [
            { type: "course", title: "Nuxt 3 Documentation", url: "#" },
        ],
        position: { x: 2000, y: 240 },
        tier: 3,
    },
    {
        id: "vue-typescript",
        title: "Vue with TypeScript",
        description: "Type-safe Vue development with TypeScript.",
        category: "vue",
        subcategory: "Advanced",
        status: "locked",
        estimatedHours: 10,
        difficulty: "advanced",
        skills: ["defineProps", "defineEmits", "Generic Components"],
        resources: [
            { type: "article", title: "Vue TypeScript Guide", url: "#" },
        ],
        position: { x: 2000, y: 160 },
        tier: 3,
    },
    {
        id: "vue-performance",
        title: "Vue Performance",
        description: "Optimize Vue applications for speed.",
        category: "vue",
        subcategory: "Performance",
        status: "locked",
        estimatedHours: 8,
        difficulty: "advanced",
        skills: ["v-memo", "shallowRef", "Virtual Scrolling"],
        resources: [
            { type: "video", title: "Vue Performance Tips", url: "#" },
        ],
        position: { x: 2000, y: 320 },
        tier: 3,
    },
    {
        id: "vue-forms",
        title: "Vue Forms",
        description: "Form handling and validation in Vue.",
        category: "vue",
        subcategory: "Forms",
        status: "locked",
        estimatedHours: 8,
        difficulty: "intermediate",
        skills: ["v-model", "VeeValidate", "FormKit"],
        resources: [
            { type: "article", title: "Vue Form Patterns", url: "#" },
        ],
        position: { x: 2000, y: 400 },
        tier: 2,
    },
    {
        id: "vue-plugins",
        title: "Vue Plugins & Ecosystem",
        description: "Extend Vue with plugins and libraries.",
        category: "vue",
        subcategory: "Ecosystem",
        status: "locked",
        estimatedHours: 6,
        difficulty: "advanced",
        skills: ["Plugin API", "VueUse", "PrimeVue"],
        resources: [
            { type: "article", title: "Vue Ecosystem Guide", url: "#" },
        ],
        position: { x: 1925, y: 480 },
        tier: 3,
    },
];
