import { ClientPersona, Industry, PersonaArchetype } from "./types";

// Industry templates
export const INDUSTRIES: Record<string, Industry> = {
    architecture: {
        id: "architecture",
        name: "Architecture",
        domain: "design",
        commonNeeds: ["Project tracking", "Client portals", "File management", "Timeline visualization"],
        terminology: { project: "engagement", client: "client", deadline: "milestone" },
        icon: "Building2",
    },
    restaurant: {
        id: "restaurant",
        name: "Restaurant & Hospitality",
        domain: "business",
        commonNeeds: ["Online ordering", "Reservation system", "Menu management", "Inventory tracking"],
        terminology: { product: "dish", order: "ticket", customer: "guest" },
        icon: "UtensilsCrossed",
    },
    ecommerce: {
        id: "ecommerce",
        name: "E-Commerce",
        domain: "business",
        commonNeeds: ["Product catalog", "Shopping cart", "Payment processing", "Order management"],
        terminology: { product: "SKU", order: "transaction", customer: "shopper" },
        icon: "ShoppingBag",
    },
    healthcare: {
        id: "healthcare",
        name: "Healthcare",
        domain: "business",
        commonNeeds: ["Patient portal", "Appointment scheduling", "Records management", "Compliance"],
        terminology: { customer: "patient", appointment: "visit", record: "chart" },
        icon: "Heart",
    },
    education: {
        id: "education",
        name: "Education",
        domain: "learning",
        commonNeeds: ["Course management", "Student tracking", "Assignment submission", "Grading"],
        terminology: { customer: "student", product: "course", order: "enrollment" },
        icon: "GraduationCap",
    },
    realestate: {
        id: "realestate",
        name: "Real Estate",
        domain: "business",
        commonNeeds: ["Property listings", "Virtual tours", "Lead management", "Contract handling"],
        terminology: { product: "listing", customer: "buyer/seller", order: "transaction" },
        icon: "Home",
    },
    consulting: {
        id: "consulting",
        name: "Consulting",
        domain: "business",
        commonNeeds: ["Time tracking", "Project management", "Client reporting", "Invoicing"],
        terminology: { product: "engagement", order: "proposal", task: "deliverable" },
        icon: "Briefcase",
    },
    nonprofit: {
        id: "nonprofit",
        name: "Non-Profit",
        domain: "business",
        commonNeeds: ["Donor management", "Event registration", "Volunteer coordination", "Impact reporting"],
        terminology: { customer: "donor", product: "program", revenue: "contributions" },
        icon: "HeartHandshake",
    },
    creativeagency: {
        id: "creativeagency",
        name: "Creative Agency",
        domain: "design",
        commonNeeds: ["Portfolio showcase", "Project collaboration", "Asset management", "Client feedback"],
        terminology: { project: "campaign", deadline: "launch", product: "creative" },
        icon: "Palette",
    },
    fitness: {
        id: "fitness",
        name: "Fitness & Wellness",
        domain: "health",
        commonNeeds: ["Class scheduling", "Member management", "Progress tracking", "Booking system"],
        terminology: { customer: "member", product: "class", order: "booking" },
        icon: "Dumbbell",
    },
};

// Persona templates - fully realized client personas
export const PERSONA_TEMPLATES: ClientPersona[] = [
    {
        id: "marcus-chen",
        name: "Marcus Chen",
        avatar: "👨‍💼",
        age: 42,
        industry: INDUSTRIES.architecture,
        role: "Principal Architect",
        companySize: "small",
        location: "Seattle, WA",
        technicalLiteracy: 2,
        decisionMaking: "deliberate",
        communication: "normal",
        patience: "medium",
        budgetSensitivity: "moderate",
        businessContext: "Running a 12-person architecture firm. Currently using spreadsheets and email to track projects, but it's becoming unmanageable as they take on more clients.",
        painPoints: ["Projects fall through cracks", "Clients ask for status updates constantly", "Junior architects don't know what's priority"],
        previousExperience: "Tried Asana but found it too complex. Team didn't adopt it.",
        messageStyle: {
            greetingStyle: ["Hi", "Hello", "Hey there"],
            signoffStyle: ["Thanks", "Best", "Cheers"],
            emojiUsage: "minimal",
            formalityLevel: "professional",
            typicalLength: "medium",
        },
        typicalResponseDelay: 4,
        preferredContactMethod: "chat",
        archetype: "detail_oriented",
    },
    {
        id: "sarah-johnson",
        name: "Sarah Johnson",
        avatar: "👩‍🍳",
        age: 35,
        industry: INDUSTRIES.restaurant,
        role: "Restaurant Owner",
        companySize: "small",
        location: "Austin, TX",
        technicalLiteracy: 1,
        decisionMaking: "quick",
        communication: "terse",
        patience: "low",
        budgetSensitivity: "strict",
        businessContext: "Owns a popular farm-to-table restaurant. Wants to expand to online ordering but has no tech background.",
        painPoints: ["Phone orders are overwhelming", "Third-party apps take huge commissions", "Menu changes are a nightmare to update"],
        previousExperience: "Uses Square for payments. That's about it.",
        messageStyle: {
            greetingStyle: ["Hey", "Hi!", "Quick question:"],
            signoffStyle: ["Thanks!", "Appreciate it", ""],
            emojiUsage: "frequent",
            formalityLevel: "casual",
            typicalLength: "short",
        },
        typicalResponseDelay: 1,
        preferredContactMethod: "chat",
        archetype: "busy_executive",
    },
    {
        id: "david-kumar",
        name: "David Kumar",
        avatar: "👨‍💻",
        age: 29,
        industry: INDUSTRIES.ecommerce,
        role: "Startup Founder",
        companySize: "solo",
        location: "San Francisco, CA",
        technicalLiteracy: 4,
        decisionMaking: "quick",
        communication: "verbose",
        patience: "medium",
        budgetSensitivity: "flexible",
        businessContext: "Serial entrepreneur launching a sustainable fashion marketplace. Has development experience but wants to move fast.",
        painPoints: ["Need to validate idea quickly", "Don't want to build everything from scratch", "Scaling concerns"],
        previousExperience: "Built two previous startups. Comfortable with code but prefers to delegate now.",
        messageStyle: {
            greetingStyle: ["Hey!", "What's up", "So..."],
            signoffStyle: ["🚀", "Let's gooo", ""],
            emojiUsage: "frequent",
            formalityLevel: "casual",
            typicalLength: "long",
        },
        typicalResponseDelay: 0.5,
        preferredContactMethod: "chat",
        archetype: "enthusiastic_founder",
    },
    {
        id: "dr-emily-watson",
        name: "Dr. Emily Watson",
        avatar: "👩‍⚕️",
        age: 48,
        industry: INDUSTRIES.healthcare,
        role: "Clinic Director",
        companySize: "medium",
        location: "Boston, MA",
        technicalLiteracy: 2,
        decisionMaking: "deliberate",
        communication: "verbose",
        patience: "high",
        budgetSensitivity: "moderate",
        businessContext: "Runs a multi-specialty clinic with 8 physicians. Needs a patient portal that meets HIPAA requirements.",
        painPoints: ["Current system is from 2010", "Patients can't access their records", "Staff spends hours on phone scheduling"],
        previousExperience: "Has used several EHR systems. Frustrated with all of them.",
        messageStyle: {
            greetingStyle: ["Good morning", "Hello", "Dear"],
            signoffStyle: ["Best regards", "Thank you", "Warm regards"],
            emojiUsage: "none",
            formalityLevel: "formal",
            typicalLength: "long",
        },
        typicalResponseDelay: 24,
        preferredContactMethod: "email",
        archetype: "detail_oriented",
    },
    {
        id: "mike-thompson",
        name: "Mike Thompson",
        avatar: "🏋️",
        age: 31,
        industry: INDUSTRIES.fitness,
        role: "Gym Owner",
        companySize: "small",
        location: "Denver, CO",
        technicalLiteracy: 3,
        decisionMaking: "indecisive",
        communication: "normal",
        patience: "medium",
        budgetSensitivity: "strict",
        businessContext: "Owns a CrossFit gym with 200 members. Wants to modernize but keeps changing his mind on features.",
        painPoints: ["Class scheduling is chaos", "Members forget to check in", "Can't track member progress"],
        previousExperience: "Uses MindBody but hates the monthly fee. Has tried 3 other systems.",
        messageStyle: {
            greetingStyle: ["Hey", "Yo", "What's good"],
            signoffStyle: ["Thanks bro", "Cheers", "💪"],
            emojiUsage: "frequent",
            formalityLevel: "casual",
            typicalLength: "medium",
        },
        typicalResponseDelay: 2,
        preferredContactMethod: "chat",
        archetype: "indecisive",
    },
    {
        id: "jennifer-martinez",
        name: "Jennifer Martinez",
        avatar: "👩‍🎨",
        age: 38,
        industry: INDUSTRIES.creativeagency,
        role: "Creative Director",
        companySize: "small",
        location: "Los Angeles, CA",
        technicalLiteracy: 3,
        decisionMaking: "deliberate",
        communication: "verbose",
        patience: "low",
        budgetSensitivity: "flexible",
        businessContext: "Runs a boutique branding agency. Obsessed with aesthetics and user experience.",
        painPoints: ["Client feedback is scattered", "Portfolio site looks dated", "Can't showcase process well"],
        previousExperience: "Team uses Figma religiously. Tried Notion but it's too ugly.",
        messageStyle: {
            greetingStyle: ["Hi there!", "Hello!", "Hey hey"],
            signoffStyle: ["xo", "Best!", "✨"],
            emojiUsage: "frequent",
            formalityLevel: "casual",
            typicalLength: "long",
        },
        typicalResponseDelay: 3,
        preferredContactMethod: "chat",
        archetype: "perfectionist",
    },
    {
        id: "robert-williams",
        name: "Robert Williams",
        avatar: "👔",
        age: 55,
        industry: INDUSTRIES.consulting,
        role: "Managing Partner",
        companySize: "medium",
        location: "Chicago, IL",
        technicalLiteracy: 2,
        decisionMaking: "deliberate",
        communication: "terse",
        patience: "low",
        budgetSensitivity: "flexible",
        businessContext: "Partner at a management consulting firm. Needs internal tools but delegates all decisions.",
        painPoints: ["Associates waste time on admin", "Can't track billable hours accurately", "Reports are manual"],
        previousExperience: "Firm uses SAP for everything. He doesn't know how it works.",
        messageStyle: {
            greetingStyle: ["", "Quick update:", "FYI:"],
            signoffStyle: ["RW", "Best", ""],
            emojiUsage: "none",
            formalityLevel: "formal",
            typicalLength: "short",
        },
        typicalResponseDelay: 48,
        preferredContactMethod: "email",
        archetype: "delegator",
    },
    {
        id: "lisa-chang",
        name: "Lisa Chang",
        avatar: "👩‍💼",
        age: 33,
        industry: INDUSTRIES.nonprofit,
        role: "Executive Director",
        companySize: "small",
        location: "Portland, OR",
        technicalLiteracy: 3,
        decisionMaking: "quick",
        communication: "normal",
        patience: "high",
        budgetSensitivity: "strict",
        businessContext: "Runs a environmental nonprofit. Every dollar matters. Needs to show impact to donors.",
        painPoints: ["Donor tracking is in spreadsheets", "Volunteer management is chaos", "Board wants better reports"],
        previousExperience: "Used Salesforce Nonprofit but it was overkill. Team found it overwhelming.",
        messageStyle: {
            greetingStyle: ["Hi!", "Hello", "Hope you're well!"],
            signoffStyle: ["Thanks so much!", "Gratefully", "Best"],
            emojiUsage: "minimal",
            formalityLevel: "professional",
            typicalLength: "medium",
        },
        typicalResponseDelay: 6,
        preferredContactMethod: "chat",
        archetype: "budget_conscious",
    },
];

// Get persona by ID
export function getPersonaById(id: string): ClientPersona | undefined {
    return PERSONA_TEMPLATES.find(p => p.id === id);
}

// Get personas by archetype
export function getPersonasByArchetype(archetype: PersonaArchetype): ClientPersona[] {
    return PERSONA_TEMPLATES.filter(p => p.archetype === archetype);
}

// Get personas by industry
export function getPersonasByIndustry(industryId: string): ClientPersona[] {
    return PERSONA_TEMPLATES.filter(p => p.industry.id === industryId);
}

// Get all industries
export function getAllIndustries(): Industry[] {
    return Object.values(INDUSTRIES);
}

// Get random persona
export function getRandomPersona(): ClientPersona {
    return PERSONA_TEMPLATES[Math.floor(Math.random() * PERSONA_TEMPLATES.length)];
}
