import type { CommunityPath } from "./communityPathsTypes";

export const MOCK_COMMUNITY_PATHS: CommunityPath[] = [
    {
        id: "path-1",
        slug: "react-mastery",
        title: "React Mastery",
        subtitle: "From Zero to Hero",
        description: "Complete React learning path covering fundamentals to advanced patterns",
        domain: "frontend",
        difficulty: "intermediate",
        pathType: "career",
        estimatedHours: 45,
        courseCount: 5,
        chapterCount: 28,
        enrollmentCount: 1842,
        creator: { id: "u1", displayName: "Sarah Chen", avatarUrl: null },
        createdAt: "2024-11-15T10:00:00Z",
        courses: [
            {
                id: "c1",
                title: "React Fundamentals",
                description: "Core concepts and JSX",
                sortOrder: 1,
                estimatedHours: 8,
                chapterCount: 5,
                chapters: [
                    { id: "ch1", title: "Introduction to React", description: null, sortOrder: 1, estimatedMinutes: 45, xpReward: 100 },
                    { id: "ch2", title: "JSX Deep Dive", description: null, sortOrder: 2, estimatedMinutes: 60, xpReward: 120 },
                    { id: "ch3", title: "Components & Props", description: null, sortOrder: 3, estimatedMinutes: 90, xpReward: 150 },
                    { id: "ch4", title: "State Management Basics", description: null, sortOrder: 4, estimatedMinutes: 120, xpReward: 200 },
                    { id: "ch5", title: "Event Handling", description: null, sortOrder: 5, estimatedMinutes: 60, xpReward: 100 },
                ],
            },
            {
                id: "c2",
                title: "Hooks Mastery",
                description: "useState, useEffect, and custom hooks",
                sortOrder: 2,
                estimatedHours: 10,
                chapterCount: 6,
                chapters: [
                    { id: "ch6", title: "useState In Depth", description: null, sortOrder: 1, estimatedMinutes: 90, xpReward: 150 },
                    { id: "ch7", title: "useEffect Patterns", description: null, sortOrder: 2, estimatedMinutes: 120, xpReward: 200 },
                    { id: "ch8", title: "useContext for State", description: null, sortOrder: 3, estimatedMinutes: 90, xpReward: 150 },
                    { id: "ch9", title: "useReducer Complex State", description: null, sortOrder: 4, estimatedMinutes: 100, xpReward: 180 },
                    { id: "ch10", title: "Custom Hooks", description: null, sortOrder: 5, estimatedMinutes: 120, xpReward: 220 },
                    { id: "ch11", title: "Performance Hooks", description: null, sortOrder: 6, estimatedMinutes: 80, xpReward: 140 },
                ],
            },
        ],
    },
    {
        id: "path-2",
        slug: "python-data-science",
        title: "Python for Data Science",
        subtitle: "Analytics & Visualization",
        description: "Master data analysis, visualization, and machine learning with Python",
        domain: "data",
        difficulty: "intermediate",
        pathType: "career",
        estimatedHours: 60,
        courseCount: 6,
        chapterCount: 35,
        enrollmentCount: 2156,
        creator: { id: "u2", displayName: "Alex Kumar", avatarUrl: null },
        createdAt: "2024-10-20T14:30:00Z",
        courses: [
            {
                id: "c3",
                title: "Python Fundamentals",
                description: "Core Python for data work",
                sortOrder: 1,
                estimatedHours: 8,
                chapterCount: 5,
                chapters: [
                    { id: "ch12", title: "Python Basics", description: null, sortOrder: 1, estimatedMinutes: 60, xpReward: 100 },
                    { id: "ch13", title: "Data Structures", description: null, sortOrder: 2, estimatedMinutes: 90, xpReward: 150 },
                    { id: "ch14", title: "Functions & Modules", description: null, sortOrder: 3, estimatedMinutes: 80, xpReward: 130 },
                    { id: "ch15", title: "File Handling", description: null, sortOrder: 4, estimatedMinutes: 70, xpReward: 110 },
                    { id: "ch16", title: "Error Handling", description: null, sortOrder: 5, estimatedMinutes: 60, xpReward: 100 },
                ],
            },
            {
                id: "c4",
                title: "Pandas & NumPy",
                description: "Data manipulation libraries",
                sortOrder: 2,
                estimatedHours: 12,
                chapterCount: 7,
                chapters: [
                    { id: "ch17", title: "NumPy Arrays", description: null, sortOrder: 1, estimatedMinutes: 90, xpReward: 150 },
                    { id: "ch18", title: "Pandas DataFrames", description: null, sortOrder: 2, estimatedMinutes: 120, xpReward: 200 },
                    { id: "ch19", title: "Data Cleaning", description: null, sortOrder: 3, estimatedMinutes: 100, xpReward: 170 },
                    { id: "ch20", title: "Data Transformation", description: null, sortOrder: 4, estimatedMinutes: 110, xpReward: 180 },
                    { id: "ch21", title: "Merging & Joining", description: null, sortOrder: 5, estimatedMinutes: 80, xpReward: 140 },
                    { id: "ch22", title: "Grouping & Aggregation", description: null, sortOrder: 6, estimatedMinutes: 90, xpReward: 150 },
                    { id: "ch23", title: "Time Series", description: null, sortOrder: 7, estimatedMinutes: 100, xpReward: 170 },
                ],
            },
        ],
    },
    {
        id: "path-3",
        slug: "nodejs-backend",
        title: "Node.js Backend Development",
        subtitle: "Build Scalable APIs",
        description: "Learn to build production-ready backend services with Node.js and Express",
        domain: "backend",
        difficulty: "intermediate",
        pathType: "skill",
        estimatedHours: 40,
        courseCount: 4,
        chapterCount: 22,
        enrollmentCount: 987,
        creator: { id: "u3", displayName: "Mike Johnson", avatarUrl: null },
        createdAt: "2024-12-01T09:00:00Z",
        courses: [
            {
                id: "c5",
                title: "Node.js Basics",
                description: "Core Node.js concepts",
                sortOrder: 1,
                estimatedHours: 6,
                chapterCount: 4,
                chapters: [
                    { id: "ch24", title: "Node.js Runtime", description: null, sortOrder: 1, estimatedMinutes: 60, xpReward: 100 },
                    { id: "ch25", title: "Modules & NPM", description: null, sortOrder: 2, estimatedMinutes: 90, xpReward: 150 },
                    { id: "ch26", title: "Async Programming", description: null, sortOrder: 3, estimatedMinutes: 120, xpReward: 200 },
                    { id: "ch27", title: "File System & Streams", description: null, sortOrder: 4, estimatedMinutes: 90, xpReward: 150 },
                ],
            },
        ],
    },
    {
        id: "path-4",
        slug: "ui-ux-design",
        title: "UI/UX Design Fundamentals",
        subtitle: "Design Thinking to Prototype",
        description: "Master the principles of user interface and experience design",
        domain: "design",
        difficulty: "beginner",
        pathType: "career",
        estimatedHours: 35,
        courseCount: 4,
        chapterCount: 20,
        enrollmentCount: 1523,
        creator: { id: "u4", displayName: "Emma Wilson", avatarUrl: null },
        createdAt: "2024-11-01T16:00:00Z",
        courses: [
            {
                id: "c6",
                title: "Design Principles",
                description: "Core design theory",
                sortOrder: 1,
                estimatedHours: 8,
                chapterCount: 5,
                chapters: [
                    { id: "ch28", title: "Visual Hierarchy", description: null, sortOrder: 1, estimatedMinutes: 75, xpReward: 120 },
                    { id: "ch29", title: "Color Theory", description: null, sortOrder: 2, estimatedMinutes: 90, xpReward: 150 },
                    { id: "ch30", title: "Typography", description: null, sortOrder: 3, estimatedMinutes: 80, xpReward: 130 },
                    { id: "ch31", title: "Layout & Spacing", description: null, sortOrder: 4, estimatedMinutes: 85, xpReward: 140 },
                    { id: "ch32", title: "Consistency Patterns", description: null, sortOrder: 5, estimatedMinutes: 70, xpReward: 110 },
                ],
            },
        ],
    },
    {
        id: "path-5",
        slug: "devops-fundamentals",
        title: "DevOps Engineering Path",
        subtitle: "CI/CD & Cloud Infrastructure",
        description: "Learn modern DevOps practices, containerization, and cloud deployment",
        domain: "devops",
        difficulty: "advanced",
        pathType: "career",
        estimatedHours: 55,
        courseCount: 5,
        chapterCount: 30,
        enrollmentCount: 678,
        creator: { id: "u5", displayName: "David Park", avatarUrl: null },
        createdAt: "2024-09-15T11:00:00Z",
        courses: [
            {
                id: "c7",
                title: "Docker Fundamentals",
                description: "Containerization basics",
                sortOrder: 1,
                estimatedHours: 10,
                chapterCount: 6,
                chapters: [
                    { id: "ch33", title: "Container Concepts", description: null, sortOrder: 1, estimatedMinutes: 60, xpReward: 100 },
                    { id: "ch34", title: "Dockerfile Best Practices", description: null, sortOrder: 2, estimatedMinutes: 90, xpReward: 150 },
                    { id: "ch35", title: "Docker Compose", description: null, sortOrder: 3, estimatedMinutes: 120, xpReward: 200 },
                    { id: "ch36", title: "Networking", description: null, sortOrder: 4, estimatedMinutes: 100, xpReward: 170 },
                    { id: "ch37", title: "Volumes & Storage", description: null, sortOrder: 5, estimatedMinutes: 80, xpReward: 140 },
                    { id: "ch38", title: "Multi-stage Builds", description: null, sortOrder: 6, estimatedMinutes: 90, xpReward: 150 },
                ],
            },
        ],
    },
    {
        id: "path-6",
        slug: "react-native-mobile",
        title: "React Native Mobile Apps",
        subtitle: "Cross-Platform Development",
        description: "Build iOS and Android apps with React Native",
        domain: "mobile",
        difficulty: "intermediate",
        pathType: "skill",
        estimatedHours: 50,
        courseCount: 5,
        chapterCount: 26,
        enrollmentCount: 892,
        creator: { id: "u6", displayName: "Lisa Zhang", avatarUrl: null },
        createdAt: "2024-10-10T08:30:00Z",
        courses: [],
    },
    {
        id: "path-7",
        slug: "fullstack-nextjs",
        title: "Fullstack with Next.js",
        subtitle: "Modern Web Development",
        description: "Build complete web applications with Next.js, React, and databases",
        domain: "fullstack",
        difficulty: "advanced",
        pathType: "career",
        estimatedHours: 70,
        courseCount: 7,
        chapterCount: 42,
        enrollmentCount: 1234,
        creator: { id: "u7", displayName: "James Miller", avatarUrl: null },
        createdAt: "2024-11-20T13:00:00Z",
        courses: [],
    },
    {
        id: "path-8",
        slug: "machine-learning-intro",
        title: "Introduction to Machine Learning",
        subtitle: "AI Fundamentals",
        description: "Start your journey into AI and machine learning with Python",
        domain: "ai-ml",
        difficulty: "intermediate",
        pathType: "career",
        estimatedHours: 65,
        courseCount: 6,
        chapterCount: 38,
        enrollmentCount: 2890,
        creator: { id: "u8", displayName: "Dr. Nina Patel", avatarUrl: null },
        createdAt: "2024-08-25T10:00:00Z",
        courses: [],
    },
    {
        id: "path-9",
        slug: "typescript-fundamentals",
        title: "TypeScript Mastery",
        subtitle: "Type-Safe JavaScript",
        description: "Master TypeScript for building robust applications",
        domain: "frontend",
        difficulty: "beginner",
        pathType: "skill",
        estimatedHours: 25,
        courseCount: 3,
        chapterCount: 15,
        enrollmentCount: 3156,
        creator: null,
        createdAt: "2024-12-10T15:00:00Z",
        courses: [],
        isEnrolled: true,
    },
    {
        id: "path-10",
        slug: "css-animations",
        title: "CSS Animations & Transitions",
        subtitle: "Beautiful Web Animations",
        description: "Create stunning animations and micro-interactions with CSS",
        domain: "design",
        difficulty: "intermediate",
        pathType: "skill",
        estimatedHours: 15,
        courseCount: 2,
        chapterCount: 10,
        enrollmentCount: 745,
        creator: { id: "u9", displayName: "Carlos Rivera", avatarUrl: null },
        createdAt: "2024-12-05T09:30:00Z",
        courses: [],
    },
];
